app:
    resource: "@AppBundle/Controller/"
    type:     annotation

queue:
    path: /queue
    defaults: { _controller: AppBundle:Queue:queue }
    
queue_submit:
    path: /submit
    defaults: { _controller: AppBundle:Queue:submit }